# This file is used only in development environment. to open ports and expose services available for development only.
services:
  app:
    # Load RoadRunner configuration for development
    command: [ "sh", "-c", "/usr/bin/rr serve -c .rr.dev.yaml" ]
    volumes:
      - .:/app
    # Disable healthcheck for development since RoadRunner is in debug mode
    healthcheck:
      # Disable healthcheck for development since RoadRunner is in debug mode
      test: ["CMD-SHELL", "exit 0"]
    ports:
      - "8080:8080"
      - "8081:8081"

  mysql:
    tmpfs:
      - /var/lib/mysql
    ports:
      - "3306:3306"
